### ISSUE TITLE
TP Finished

### ISSUE THREAD

**Issue by SachaLhopital** [PolytechLyon/4a-isi3-tp2-2016-2017-groupe-1-lafaye_lhopital#1]
TP2 prêt pour correction @Slashgear ! 
Bonne semaine !

**Comment by Slashgear** [comment]
Hello, rien à redire sur ce TP 👏 

💡 Si vous avez un peu de temps et de motivation. Vous pouvez essayer de mettre en pratique des tests unitaires sur votre projet 😉

**Comment by SachaLhopital** [comment]
👍
